name: my_music_game_f
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluttery: ^0.0.7
  fluttery_audio: ^0.0.3
  flame: ^0.8.4
  sqflite: any
  #flutter_charts:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/piano_A.mp3
    - assets/audio/piano_A_sharp.mp3
    - assets/audio/piano_B.mp3
    - assets/audio/piano_middle_C.mp3
    - assets/audio/piano_C_sharp.mp3
    - assets/audio/piano_D.mp3
    - assets/audio/piano_D_sharp.mp3
    - assets/audio/piano_E.mp3
    - assets/audio/piano_F.mp3
    - assets/audio/piano_G.mp3
    - assets/audio/piano_G_sharp.mp3
    - assets/audio/piano_48.mp3
    - assets/audio/piano_49.mp3
    - assets/audio/piano_50.mp3
    - assets/audio/piano_51.mp3
    - assets/audio/piano_52.mp3
    - assets/audio/piano_53.mp3
    - assets/audio/piano_54.mp3
    - assets/audio/piano_55.mp3
    - assets/audio/piano_56.mp3
    - assets/audio/piano_57.mp3
    - assets/audio/piano_58.mp3
    - assets/audio/piano_59.mp3
    - assets/audio/piano_60.mp3
    - assets/audio/piano_61.mp3
    - assets/audio/piano_62.mp3
    - assets/audio/piano_63.mp3
    - assets/audio/piano_64.mp3
    - assets/audio/piano_65.mp3
    - assets/audio/piano_66.mp3
    - assets/audio/piano_67.mp3
    - assets/audio/piano_68.mp3
    - assets/audio/piano_69.mp3
    - assets/audio/piano_70.mp3
    - assets/audio/piano_71.mp3
    - assets/audio/piano_72.mp3
    - assets/audio/Bing-sound.mp3



  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
